apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "comments-system.fullname" . }}-backend-api
  labels:
    app: comments
    component: backend-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "comments-system.fullname" . }}-backend-api
  minReplicas: {{ .Values.hpa.backendApi.minReplicas | default 1 }}
  maxReplicas: {{ .Values.hpa.backendApi.maxReplicas | default 5 }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.backendApi.targetCPUUtilizationPercentage | default 50 }}