{{- $fullname := include "comments-system.fullname" . }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $fullname }}-deny-all
  labels:
    app: comments
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $fullname }}-allow-frontend-to-backendapi
  labels:
    app: comments
spec:
  podSelector:
    matchLabels:
      app: comments
      component: backend-api
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: comments
              component: frontend
      ports:
        - protocol: TCP
          port: {{ .Values.service.backendApi.port | default 5000 }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $fullname }}-allow-backendapi-to-backenddata
  labels:
    app: comments
spec:
  podSelector:
    matchLabels:
      app: comments
      component: backend-data
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: comments
              component: backend-api
      ports:
        - protocol: TCP
          port: {{ .Values.service.backendData.port | default 5001 }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $fullname }}-allow-backenddata-to-mongo
  labels:
    app: comments
spec:
  podSelector:
    matchLabels:
      app: comments
      component: database
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: comments
              component: backend-data
      ports:
        - protocol: TCP
          port: 27017