apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "comments-system.fullname" . }}-frontend
  labels:
    app: comments
    component: frontend
spec:
  to:
    kind: Service
    name: {{ include "comments-system.fullname" . }}-frontend
  port:
    targetPort: {{ .Values.service.frontend.port | default 8080 }}
{{- if and .Values.route (gt (len (default "" .Values.route.host)) 0) }}
  host: {{ .Values.route.host | quote }}
{{- end }}
{{- if .Values.route.tls.enabled }}
  tls:
    termination: {{ .Values.route.tls.termination | default "edge" }}
{{- end }}