apiVersion: v1
kind: Secret
metadata:
  name: {{ include "comments-system.fullname" . }}-mongo-secret
  labels:
    app: comments
    component: database
type: Opaque
stringData:
  mongo-user: {{ .Values.mongodb.user }}
  mongo-pass: {{ .Values.mongodb.password }}
