apiVersion: v1
kind: Secret
metadata:
  name: {{ include "comments-system.fullname" . }}-mongo
  labels:
    app: comments
type: Opaque
stringData:
  {{- if .Values.mongodb.user }}
  mongo-user: {{ .Values.mongodb.user | quote }}
  {{- end }}
  {{- if .Values.mongodb.password }}
  mongo-password: {{ .Values.mongodb.password | quote }}
  {{- end }}
  {{- if .Values.mongodb.database }}
  mongo-database: {{ .Values.mongodb.database | quote }}
  {{- else }}
  mongo-database: "commentsdb"
  {{- end }}