apiVersion: v1
kind: Service
metadata:
  name: {{ include "comments-system.fullname" . }}-mongo
  labels:
    app: comments
    component: database
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: comments
    component: database
  type: ClusterIP
