apiVersion: v1
kind: Service
metadata:
  name: {{ include "comments-system.fullname" . }}-frontend
  labels:
    app: comments
    component: frontend
spec:
  ports:
    - port: {{ .Values.service.frontend.port | default 8080 }}
      targetPort: {{ .Values.service.frontend.port | default 8080 }}
  selector:
    app: comments
    component: frontend
  type: {{ .Values.service.type | default "ClusterIP" }}