apiVersion: v1
kind: Service
metadata:
  name: {{ include "comments-system.fullname" . }}-frontend
  labels:
    app: comments
    component: frontend
spec:
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: {{ .Values.service.frontend.port }}
  selector:
    app: comments
    component: frontend
  type: ClusterIP
