apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "comments-system.fullname" . }}-mongo
  labels:
    app: comments
    component: database
spec:
  serviceName: {{ include "comments-system.fullname" . }}-mongo
  replicas: {{ .Values.replicaCount.mongo | default 1 }}
  selector:
    matchLabels:
      app: comments
      component: database
  template:
    metadata:
      labels:
        app: comments
        component: database
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: mongo
          image: "{{ .Values.mongodb.image | default "mongo:6.0" }}"
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              value: {{ (.Values.mongodb.database | default "commentsdb") | quote }}
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "comments-system.fullname" . }}-mongo
                  key: mongo-user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "comments-system.fullname" . }}-mongo
                  key: mongo-password
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
        labels:
          app: comments
          component: database
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.mongodb.storage | default "5Gi" }}